[project]
name = "todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "questionary>=2.1.1",
    "typer>=0.24.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.4",
    "ty>=0.0.1a26",
]

[tool.coverage.run]
branch = true
source = ["src"]
omit = [
  "*/__init__.py",
  "*/tests/*",
  "*/alembic/*",
  "*/migrations/*",
  "*/.venv/*",
]

[tool.coverage.report]
precision = 2
skip_covered = true
show_missing = true
exclude_lines = [
  "pragma: no cover",
  "if __name__ == .__main__.:",
  "raise NotImplementedError",
  "abstractmethod",
  "pass",
]

[tool.coverage.xml]
output = "coverage.xml"

[tool.coverage.html]
directory = "htmlcov"

[tool.ty.src]
exclude = [
  ".pytest_cache/",
  ".ruff_cache/",
  "__pycache__/",
]
